#!/usr/bin/env bash
# Checking if no of parameters is less than 4

if [ $ -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning parameters to variables

path_to_file=$1
ip=$2
user_name=$3
path_to_ssh_key=$4

# Disabling strict host key checking

scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$user_name@$ip:~/"

# Checking if the transfer was successful
if [ $? -eq 0 ]
then
	echo "File transfer Successful"
else
	echo "File not transfer"
fi
