#!/usr/bin/env bash

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Check if UFW is active and then allow 'Nginx HTTP' through firewall
sudo ufw status | grep -qw active && sudo ufw allow 'Nginx HTTP'

# Write 'Hello World!' to the default Nginx index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configuration for any errors
sudo nginx -t

# Restart Nginx service using 'service' instead of 'systemctl'
sudo service nginx restart
