#!/usr/bin/env bash
# Installation of nginx web server

# Update package lists
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Allow 'Nginx HTTP' through firewall
sudo ufw allow 'Nginx HTTP'

# Write 'Hello World!' to the default Nginx index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Test Nginx configuration for any errors
sudo nginx -t

# Restart Nginx service
sudo service nginx reload
