#!/usr/bin/env bash
# Custom 404 page that contains the string Ceci n'est pas une page
# Update package list and install nginx
sudo apt-get update
sudo apt-get install -y nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
# Define the replacement string for the redirection configuration
string_for_replacement="server_name _;\n\trewrite ^/redirect_me https://google.com/ permanent;"
# Insert the replacement string into the Nginx configuration
sudo sed -i "s|server_name _;|$string_for_replacement|" /etc/nginx/sites-enabled/default
# Define the string for the custom 404 page configuration
string_for_replacement2="listen 80 default_server;\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
# Use sed to insert the configuration for the custom 404 page
sudo sed -i "s|listen 80 default_server;|$string_for_replacement2|" /etc/nginx/sites-enabled/default
# Create the custom 404.html file
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# Test the Nginx configuration
sudo nginx -t
# Reload Nginx to apply the changes
sudo service nginx restart
